config/routes.rb
Mortgage2::Application.routes.draw do

  devise_for :users do
    get '/logout' => 'devise/sessions#destroy', :as => "destroy_user_session"
  end

  resources :users

  root to: 'static_pages#home'

  get '/thanks', to: 'static_pages#thanks'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :zipcode, :home_value, :mortgage_balance, :street, :state, :city, :name, :email, :phone
  attr_accessible :password
  
  validates :zipcode, presence: true
  validates_format_of :zipcode, :with => /^\d{5}(-\d{4})?$/, :message => "Please enter a correct zipcode"

  validates :home_value, presence: true
  validates :mortgage_balance, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  validates :phone, presence: true, :numericality => { :only_integer => true },  :length => { :is => 10 }

  validates :name, presence: true  
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_out_path_for(resource)
  	if current_user
	  	if current_user.phone != nil
	  		thanks_path
	  	else
	  		root_path
	  	end
	else
		root_path
	end
  end

  def after_sign_in_path_for(resource)
  	if current_user.email == "vpujji@gmail.com"
  		'/users'
  	else
  		'/logout'
  	end
  end

  def authorize
  	if current_user
	  	unless current_user.email == "vpujji@gmail.com"
	  		redirect_to new_user_session_path
	  	end
	else 
		redirect_to new_user_session_path
	end
  end

end

app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

	def create
    build_resource

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		if current_user
			@user = current_user
		else
			@user = User.new
		end
	end

	def thanks
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, :except => [:new, :create, :edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/logout', notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to '/logout', notice: 'User was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
		:user
    end


	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

	def home_value_options
		[
			["0-$150,000", "0-$150,000"],
			["$150,000-$300,000", "$150,000-$300,000"],
			["$300,000-$500,000", "$300,000-$500,000"],
			["$500,000-$750,000", "$500,000-$750,000"],
			["$750,000-$1,000,000","$750,000-$1,000,000"],
			["$1,000,000+","$1,000,000+"]
		]
	end

	def mortgage_balance_options
		[
			["0-$150,000", "0-$150,000"],
			["$150,000-$300,000", "$150,000-$300,000"],
			["$300,000-$500,000", "$300,000-$500,000"],
			["$500,000-$750,000", "$500,000-$750,000"],
			["$750,000-$1,000,000","$750,000-$1,000,000"],
			["$1,000,000+","$1,000,000+"]
		]
	end
	
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Free Reverse Mortgage Guide</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<div class="full-width-banner">
	<div class="container">
		<div class="row">
			<div class="span6">
				<div class="logo">
					<img src="/assets/logo.png" width="500px">
				</div>
				<div class="phone">
					Call Toll Free: <span style="font-weight:bold">(888) 690-3316</span>
				</div>
			</div>
			<div class="span3 offset3">
				<img src="/assets/house.png" class="house">
			</div>
		</div>
	</div>
</div>
<%= yield %>
<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-39819677-2']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
</script>
<script type="text/javascript">
function woopraReady(tracker) {
    tracker.setDomain('guide.reversemortgageselect.com');
    tracker.setIdleTimeout(1800000);
    tracker.track();
    return false;
}
(function() {
    var wsc = document.createElement('script');
    wsc.src = document.location.protocol+'//static.woopra.com/js/woopra.js';
    wsc.type = 'text/javascript';
    wsc.async = true;
    var ssc = document.getElementsByTagName('script')[0];
    ssc.parentNode.insertBefore(wsc, ssc);
})();
</script>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="container">
	<div class="first-title">
		Looking for the Best Reverse Mortgage?
	</div>
	<div class="second-title">
		Learn how to Eliminate your Mortgage Payments with a Reverse Mortgage
	</div>	
</div>
<div class="container">
	<div class="row">
		<div class="span7">
			<div class="bottom-info">
				<div class="more-info-title">
					All Credit Types
				</div>
				With a reverse mortgage, you can qualify regardless of your credit! Get the <span class="emp-text">free guide</span> to learn more today and schedule a <span class="emp-text">free consultation</span> with a financial advisor.
				<div class="more-info-title">
					No Income Required
				</div>
				With federally-insured reverse mortgages, there are <span class="emp-text">NO income or medical requirements</span>. So regardless of your current situation, you can qualify.
				<div class="more-info-title">
					Disbursement Options
				</div>
				A reverse mortgage can provide <span class="emp-text">flexible monthly income</span> to the borrower for as long as they occupy the home. Learn about the six different ways you can receive income.
				<div class="more-info-title">
					Age Eligibility
				</div>
				Reverse mortgages are designed for homeowners at least <span class="emp-text">62 years of age</span> with moderate to significant equity in their homes. Learn more with your <span class="emp-text">free guide</span>.
			</div>
		</div>
		<div class="span3 offset1" style="margin-top:-110px;">
			<img src="/assets/arrow.png" class="arrow">
			<div class="sign-up-box">
				<div class="free-guide">
					Order your FREE DVD and eBook Now
				</div>
				<div class="form-part-1">
					<%= form_for User.new, :validate => true, :html => {:id => "form1"} do |f| %>
						<%= f.label :home_value, 'The value of your home is:' %>
						<%= f.select :home_value, home_value_options, :validate => { presence: true } %>
						<div class="message" id="home_value_error"></div>
						<%= f.label :mortgage_balance, 'Your mortgage balance is:' %>
						<%= f.select :mortgage_balance, mortgage_balance_options %>
						<div class="message" id="mortgage_balance_error"></div>
						<%= f.label :zipcode %>
						<%= f.text_field :zipcode, placeholder: "Zipcode" %>
						<div class="message" id="zip_error"></div>
						<%= f.label :name %>
						<%= f.text_field :name, placeholder: "Name" %>
						<%= f.label :email %>
						<%= f.text_field :email, placeholder: "Email" %>
						<div class="message" id="email_error"></div>
						<%= f.label :phone %>
						<%= f.text_field :phone, placeholder: "Phone" %>
						<div class="message" id="phone_error"></div>
							<%= f.submit "Claim Offer >>", :class => "submit", :id => "submit-part-1" %>
					<% end %>
				</div>
			</div>
			<img src="/assets/bbb.png" class="bbb">
		</div>
	</div>
</div>

app/views/static_pages/thanks.html.erb
<% content_for :head do %>
		<script type="text/javascript">
		var fb_param = {};
		fb_param.pixel_id = '6012456584340';
		fb_param.value = '0.00';
		(function(){
		  var fpw = document.createElement('script');
		  fpw.async = true;
		  fpw.src = '//connect.facebook.net/en_US/fp.js';
		  var ref = document.getElementsByTagName('script')[0];
		  ref.parentNode.insertBefore(fpw, ref);
		})();
		</script>
		<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6012456584340&amp;value=0" /></noscript>
<% end %>


<div class="container" align="center">
	<div class="sign-up-box" style="margin-top:50px;">
			<div class="free-guide">
				Thanks for signing up!
				<br>
				<br>
				A professional financial consultant will contact you soon.
			</div>
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form2.html.erb
<div class="form-part-2">
	<%= form_for @user, :remote => :true, :method => :put, :html => {:id => "form2" } do |f| %>
		<div class="row">
			<div class="span2">
				<%= f.label :email %>
				<%= f.text_field :email, placeholder: "Email", :style => "width:90px;" %>
				<div class="message" id="email_error"></div>
			</div>
			<div class="span2">
				<%= f.label :zipcode %>
				<%= f.text_field :zipcode, placeholder: "Zipcode", :style => "width:90px;" %>
				<div class="message" id="zip_error"></div>
			</div>
		</div>
		<%= f.submit 'Next', :class => "submit", :id => "submit-part-2" %>
	<% end %>
	<div class="back-link" id="back-link-1">Back</div>
</div>
<script type="text/javascript">
	$('input#user_email').blur(function(event){
		var email_format = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i
		if (!email_format.test($('input#user_email').val())) {
			event.preventDefault();
			$('#email_error').empty().append("Please enter a valid email");
		}
		if (email_format.test($('input#user_email').val())) {
			$('#email_error').empty();
		}
	});
	$('input#user_zipcode').blur(function(event){
		var zipRegex = /^\d{5}$/;
		if (!zipRegex.test($('input#user_zipcode').val())) {
			event.preventDefault();
			$('#zip_error').empty().append("Please enter a valid zipcode");
		}
		if (zipRegex.test($('input#user_zipcode').val())) {
			$('#zip_error').empty();
		}
	});
	$('#submit-part-2').click(function(event){
		var zipRegex = /^\d{5}$/;
		if (!zipRegex.test($('input#user_zipcode').val())) {
			event.preventDefault();
			$('#zip_error').empty().append("Please enter a valid zipcode");
		}
		var email_format = /^\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i
		if (!email_format.test($('input#user_email').val())) {
			event.preventDefault();
			$('#email_error').empty().append("Please enter a valid email");
		}
	});
	$('#back-link-1').click(function(){
		$('.form-part-2').hide();
		$('.form-part-1').show().insertAfter('div.free-guide');
	});
</script>

app/views/users/_form3.html.erb
<div class="form-part-3">
	<%= form_for @user, :method => :put, :html => {:id => "form3" } do |f| %>
	<div class="row">
		<div class="span1">
				<%= f.label :name %>
				<%= f.text_field :name, placeholder: "Name", :style => "width:90px;" %>
		</div>
		<div class="span1 one-line-form">
				<%= f.label :phone %>
				<%= f.text_field :phone, placeholder: "Phone", :style => "width:90px;" %>
		</div>
	</div>
	<div class="row">
		<div class="span2" style="width:102px;">
			<div class="message" id="name_error"></div>
		</div>
		<div class="span2" style="width:102px;">
			<div class="message" id="phone_error"></div>
		</div>
	</div>
				<%= f.submit 'Submit!', :class => "submit", :id => "submit-part-3" %>
	<% end %>
	<div class="back-link" id="back-link-2">Back</div>
</div>
<script type="text/javascript">
	$('input#user_name').blur(function(event){
		if ($('input#user_name').val().length < 1) {
			event.preventDefault();
			$('#name_error').empty().append("Please enter your name");
		}
		if ($('input#user_name').val().length > 0) {
			$('#name_error').empty();
		}
	});
	
	$('input#user_phone').blur(function(event){
		if ($('input#user_phone').val().replace(/\D+/g,'').length != 10) {
			event.preventDefault();
			$('#phone_error').empty().append("Please enter your phone number");
		}
		if ($('input#user_phone').val().replace(/\D+/g,'').length == 10) {
			$('#phone_error').empty();
		}
	});
	$('#submit-part-3').click(function(event){
		if ($('input#user_name').val().length < 1) {
			event.preventDefault();
			$('#name_error').empty().append("Please enter your name");
		}
		if ($('input#user_phone').val().replace(/\D+/g,'').length != 10) {
			event.preventDefault();
			$('#phone_error').empty().append("Please enter your phone number");
		}
	});
	$('#back-link-2').click(function(){
		$('.form-part-3').hide();
		$('.form-part-2').show().insertAfter('div.free-guide');
	});
</script>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
<h1>Leads</h1>

<table>
  <tr>
    <th>Zipcode</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Home Value</th>
    <th>Mortgage Balance</th>
    <th>Time Created</th>
  </tr>
<% @users.each do |user| %>
  <tr>
    <td><%=user.zipcode%></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= user.home_value %></td>
    <td><%= user.mortgage_balance %></td>
    <td><%= user.created_at %></td>
  </tr>
<% end %>
</table>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/update.js.erb
$('.form-part-2').hide();
$('.form-part-3').show().insertAfter('div.free-guide');
$('#form3').attr('action','/users/' + '<%=current_user.id%>');
$('.bar').attr('style', 'width:85%;');